apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-nirjon-xyz
spec:
  dnsNames:
    - "*.nirjon.xyz"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: wildcard-nirjon-xyz-tls-cert
