apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: oracle-lb
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        annotations:
          oci.oraclecloud.com/oci-network-security-groups: ocid1.networksecuritygroup.oc1.ap-singapore-1.aaaaaaaar2u6zs6ntp7wk45dpzqsbmouqmltxs54qyxphc5uyo6o7aexn43q
          service.beta.kubernetes.io/oci-load-balancer-shape: flexible
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
          service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
      envoyDeployment:
        container:
          resources:
            requests:
              cpu: 25m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
