apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: oci-private-subnet
  namespace: tailscale
spec:
  replicas: 1
  hostnamePrefix: oci-private-subnet
  subnetRouter:
    advertiseRoutes:
      - "10.0.1.0/24"
