apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab

resources:
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - dns-service.yaml
  - web.yaml

configMapGenerator:
  - name: adguard-seed
    files:
      - AdGuardHome.yaml=config/AdGuardHome.yaml.tmpl
