apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-web-password
  namespace: lab
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: adguard-web-password
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: password
      remoteRef:
        key: adguard-web-password
        version: CURRENT
        decodingStrategy: None
