apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github
spec:
  type: github
  address: https://github.com/m3h3d1/oci-cloud-k8s
  secretRef:
    name: fluxcd-github-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack
spec:
  type: slack
  secretRef:
    name: fluxcd-slack-webhook
