apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tavily-api-key
  namespace: lab
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: tavily-api-key
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: api-key
      remoteRef:
        key: tavily-api-key
        version: CURRENT
        decodingStrategy: None
