- name: Startpage
  width: slim
  hide-desktop-navigation: false
  center-vertically: true
  columns:
    - size: full
      widgets:
        - type: search
          autofocus: true

        - type: monitor
          cache: 5m
          title: Services
          sites:
            - title: Glance
              url: "${GLANCE_URL}"
              icon: si:glance
            - title: Lychee
              url: "${LYCHEE_URL}"
              icon: si:imagetoolbox
            - title: Grafana
              url: "${GRAFANA_URL}"
              icon: si:grafana
            - title: Teleport
              url: "${TELEPORT_URL}"
              icon: si:circle
            - title: Longhorn
              url: "${LONGHORN_URL}"
              icon: si:longhorn
            - title: Boutique
              url: "${BOUTIQUE_URL}"
              icon: si:homeassistantcommunitystore

        - type: bookmarks
          groups:
            - title: Cluster Management
              links:
                - title: Longhorn
                  url: "${LONGHORN_URL}"
                - title: Grafana
                  url: "${GRAFANA_URL}"
                - title: Teleport
                  url: "${TELEPORT_URL}"
            - title: General
              links:
                - title: GitHub
                  url: https://github.com/
                - title: Google
                  url: https://google.com
