apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab

resources:
  - deployment.yaml

configMapGenerator:
  - name: glance-config
    files:
    files:
      - config/glance.yml
      - config/home.yml
      - config/startpage.yml
      - config/media.yml
      - config/games.yml
  - name: glance-assets
    files:
      - assets/user.css
