apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-values
  namespace: tailscale
spec:
  refreshInterval: 3m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: tailscale-operator-values
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        values.yaml: |
          oauth:
            clientId: "{{ .clientId }}"
            clientSecret: "{{ .clientSecret }}"
          operatorConfig:
            defaultTags: "tag:k8s-operator"
          proxyConfig:
            defaultTags: "tag:k8s"
  data:
    - secretKey: clientId
      remoteRef:
        key: tailscale-oauth-client-id
        version: CURRENT
        decodingStrategy: None
    - secretKey: clientSecret
      remoteRef:
        key: tailscale-oauth-client-secret
        version: CURRENT
        decodingStrategy: None
